
import { PaintItem, Transaction } from './types';

export const INITIAL_PAINTS: PaintItem[] = [
  {
    id: '1',
    name: 'Branco Ártico - Brilhante',
    category: 'Alvenaria',
    type: 'Brilhante',
    colorHex: '#F0F8FF',
    sku: 'OB-G24-X',
    quantity: 1240,
    unit: 'Galões',
    minStock: 100,
  },
  {
    id: '2',
    name: 'Branco Fosco - Interior',
    category: 'Interior',
    type: 'Fosco',
    colorHex: '#FFFFFF',
    sku: 'MW-I12-P',
    quantity: 45.5,
    unit: 'Unidades',
    minStock: 50,
  },
  {
    id: '3',
    name: 'Azul Oceano - Acetinado',
    category: 'Exterior',
    type: 'Acetinado',
    colorHex: '#0077be',
    sku: 'OB-G25-B',
    quantity: 120,
    unit: 'Galões',
    minStock: 30,
  },
  {
    id: '4',
    name: 'Laranja Pôr do Sol',
    category: 'Esmalte',
    type: 'Acetinado',
    colorHex: '#f59e0b',
    sku: 'SO-S55-B',
    quantity: 85,
    unit: 'Latas',
    minStock: 10,
  },
  {
    id: '5',
    name: 'Primer Eco-Verde',
    category: 'Fundo',
    type: 'Fundo',
    colorHex: '#10b981',
    sku: 'EG-P01-M',
    quantity: 200,
    unit: 'Litros',
    minStock: 25,
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    itemId: '1',
    itemName: 'Branco Ártico - Brilhante',
    type: 'IN',
    quantity: 20,
    unit: 'Litros',
    responsible: 'João Silva',
    docNumber: '#INV-90210',
    date: '2023-10-04',
    time: '10:45 AM',
    colorHex: '#F0F8FF',
  },
  {
    id: 't2',
    itemId: '2',
    itemName: 'Carmesim Fosco - Interior',
    type: 'OUT',
    quantity: 5.5,
    unit: 'Litros',
    responsible: 'Sarah Connor',
    docNumber: '#ORD-44521',
    date: '2023-10-04',
    time: '09:15 AM',
    colorHex: '#990000',
  },
  {
    id: 't3',
    itemId: '3',
    itemName: 'Azul Oceano - Acetinado',
    type: 'OUT',
    quantity: 12,
    unit: 'Litros',
    responsible: 'Ricardo Mendes',
    docNumber: '#ORD-44519',
    date: '2023-10-03',
    time: '04:30 PM',
    colorHex: '#0077be',
  }
];
